development:
  adapter: mysql2
  encoding: utf8
  database: gearo_worship_development
  pool: 10
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: gearo_worship_test
  pool: 10
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: gearo_worship_production
  pool: 10
  username: root
  password:
  host: localhost
